import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Roboto,
  Roboto_Condensed,
  Ubuntu,
  JetBrains_Mono,
} from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { LayoutProvider } from "@/hooks/use-layout";
import { ThemeProvider } from "@/components/theme-provider";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});
const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
});
const ubuntu = Ubuntu({
  weight: "400",
});
const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning data-scroll-behavior="smooth">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.layout) {
                  document.documentElement.classList.add('layout-' + localStorage.layout)
                }
              } catch (_) {}
            `,
          }}
        />
      </head>
      <body
        className={`${robotoCondensed.className} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LayoutProvider>
            <div className="bg-background relative z-10 flex min-h-svh flex-col">
              <SiteHeader />
              <main className="flex flex-1 justify-center flex-col">
                {children}
              </main>
              <SiteFooter />
            </div>
            <Toaster
              richColors
              position="top-center"
              toastOptions={{
                style: {
                  fontFamily: "Roboto Condensed, sans-serif",
                },
              }}
            />
          </LayoutProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
